#!/bin/bash
commit_message=$(cat "$1")

if [[ ! $commit_message =~ ^DJ-[0-9]{1,5}: ]]; then
    echo "Error: Commit message must start with 'DJ-X:' or 'DJ-XXXX:', where X is a number from 0 to 100000."
    exit 1
fi
